### ISSUE TITLE
High Scores Component

### ISSUE THREAD

**Issue by themarkfullton** [Lucky-Cat-Gamers/gamegame#53]
# Tasks
- [x] Create a menu that can be loaded from game
- [x] Draw top 10 users from the scores database
- [x] Style High Scores Component
- [x] Create a close menu button
